
CREATE  TABLE IF NOT EXISTS `blebeacon_DEVICE` (
  `blebeacon_DEVICE_ID` VARCHAR(45) NOT NULL ,
  `DEVICE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`blebeacon_DEVICE_ID`) )
ENGINE = InnoDB;




